name: "Install"
description: "Sets up Bun and runs install"

runs:
  using: composite
  steps:
    - name: Install bun
        uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      shell: bash
      run: bun install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
