name: Build, Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  # To use Remote Caching, uncomment the next lines and follow the steps below.
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}

jobs:
  build:
    timeout-minutes: 15
    name: Build
    runs-on: ubuntu-latest-16

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Install
        uses: ./.github/composite-actions/install

      - run: bun run build

  lint:
    timeout-minutes: 15
    name: Lint Packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install
        uses: ./.github/composite-actions/install
      - run: bun run lint

  test:
    timeout-minutes: 15
    name: Unit Tests
    runs-on: ubuntu-latest-16
    needs: build
    steps:
      
      - name: Install
        uses: ./.github/composite-actions/install
      - run: bun run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/sdk/coverage/evm/lcov.info,./packages/sdk/coverage/solana/lcov.info,

  e2e:
    timeout-minutes: 15
    name: E2E Tests
    runs-on: ubuntu-latest-16
    needs: build
    steps:
      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: bunx playwright install --with-deps

      - name: Run e2e tests
        run: bun run e2e
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          CLI_E2E_API_KEY: ${{ secrets.CLI_E2E_API_KEY }}
